### ISSUE TITLE
acceptor: sometime assert on expecting X224 but get FastPath 

### ISSUE THREAD

**Issue by elmarco** [Devolutions/IronRDP#220]
Sometime, mstsc fails to connect to the server:

```
2023-10-16T10:33:33.038633Z DEBUG ironrdp_acceptor: Wait for PDU acceptor.state="ConnectionFinalization" hint=X224Hint
2023-10-16T10:33:33.038638Z TRACE ironrdp_acceptor: PDU received length=40
2023-10-16T10:33:33.038644Z DEBUG ironrdp_acceptor::finalization: Received ShareControlHeader { share_control_pdu: Data(ShareDataHeader { share_data_pdu: Control(ControlPdu { action: Cooperate, grant_id: 0, control_id: 0 }), stream_priority: Low, compression_flags: CompressionFlags(0x0), compression_type: K8 }), pdu_source: 1002, share_id: 0 }
[crates/ironrdp-acceptor/src/finalization.rs:62] &self.state = WaitRequestControl
2023-10-16T10:33:33.038652Z DEBUG ironrdp_acceptor: Wait for PDU acceptor.state="ConnectionFinalization" hint=X224Hint
2023-10-16T10:33:33.038657Z TRACE ironrdp_acceptor: PDU received length=40
2023-10-16T10:33:33.038662Z DEBUG ironrdp_acceptor::finalization: Received ShareControlHeader { share_control_pdu: Data(ShareDataHeader { share_data_pdu: Control(ControlPdu { action: RequestControl, grant_id: 0, control_id: 0 }), stream_priority: Low, compression_flags: CompressionFlags(0x0), compression_type: K8 }), pdu_source: 1002, share_id: 0 }
[crates/ironrdp-acceptor/src/finalization.rs:62] &self.state = WaitFontList
2023-10-16T10:33:33.038670Z DEBUG ironrdp_acceptor: Wait for PDU acceptor.state="ConnectionFinalization" hint=X224Hint
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `FastPath`,
 right: `X224`', crates/ironrdp-pdu/src/lib.rs:338:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:229:5
   4: <ironrdp_pdu::X224Hint as ironrdp_pdu::PduHint>::find_size
             at ./crates/ironrdp-pdu/src/lib.rs:338:17
   5: ironrdp_async::framed::Framed<S>::read_by_hint::{{closure}}
             at ./crates/ironrdp-async/src/framed.rs:164:19
   6: ironrdp_acceptor::single_accept_state::{{closure}}
             at ./crates/ironrdp-acceptor/src/lib.rs:85:14
   7: ironrdp_acceptor::accept_finalize::{{closure}}
             at ./crates/ironrdp-acceptor/src/lib.rs:62:62
   8: ironrdp_server::server::RdpServer::run_connection::{{closure}}
             at ./crates/ironrdp-server/src/server.rs:99:92
   9: ironrdp_server::server::RdpServer::run::{{closure}}
             at ./crates/ironrdp-server/src/server.rs:117:57
  10: server::run::{{closure}}
```
Indeed, there seems to be some input messages before the FontList:
![Screenshot from 2023-10-16 14-37-14](https://github.com/Devolutions/IronRDP/assets/9381/711f6ada-8a85-40c3-85b5-b2d990b4d99c)

**Comment by elmarco** [comment]
In 1.3.1.1, "Connection Sequence", it says:
Once the client has sent the Confirm Active PDU, it can start sending mouse and keyboard input to
the server, and upon receipt of the Font List PDU the server can start sending graphics output to
the client

So we shouldn't wait for the connection finalization (FontList/FontMap) to expect such messages.

**Comment by elmarco** [comment]
@mihneabuz would you have interest fixing this? I guess we need to refactor accept_finalize / client_loop somehow.

thanks

**Comment by CBenoit** [comment]
One avenue is to accumulate such packets into a `Vec`, return them from `accept_finalize` and batch process it at the end before running the client_loop

**Comment by mihneabuz** [comment]
Sure, I can look into it
