### ISSUE TITLE
Panic in PreconnectionPdu::from_buffer

### ISSUE THREAD

**Issue by ekse** [Devolutions/IronRDP#24]
A panic was found by fuzzing PreconnectionPdu::from_buffer.

Test case: [minimized-from-28e574a2945e691cffc674ed7d6319d255d3f275.zip](https://github.com/Devolutions/IronRDP/files/4395675/minimized-from-28e574a2945e691cffc674ed7d6319d255d3f275.zip)
Branch: https://github.com/Devolutions/IronRDP/tree/fuzz-preconnection-pdu

```
cargo +nightly fuzz run fuzz_pdu minimized-from-28e574a2945e691cffc674ed7d6319d255d3f275

thread '<unnamed>' panicked at 'assertion failed: n <= self.len()', /home/sduquette/Devolutions/Wayk/IronRDP/ironrdp/src/utils.rs:247:9
#16 _$LT$$RF$$u5b$T$u5d$$u20$as$u20$ironrdp..utils..SplitTo$GT$::split_to::hfc5e768e087fe588 /home/sduquette/Devolutions/Wayk/IronRDP/ironrdp/src/utils.rs:247:9
#15 0x5616cf635310 in _$LT$ironrdp..preconnection..PreconnectionPdu$u20$as$u20$ironrdp..PduBufferParsing$GT$::from_buffer_consume::h01c56dbd8c3b66e6 /home/sduquette/Devolutions/Wayk/IronRDP/ironrdp/src/preconnection.rs:56:37
#16 0x5616cf5a2454 in ironrdp::PduBufferParsing::from_buffer::h558dcc3f32184fe2 /home/sduquette/Devolutions/Wayk/IronRDP/ironrdp/src/lib.rs:42:9
```
In the crash case, the input data ends at the `size` value that is read in PreconnectionPdu::from_buffer_consume. `size * 2` is past the end of buffer, which is then of size 0. 

```rust
            Version::V2 => {
                let size = buffer.read_u16::<LittleEndian>()? as usize;
                let payload_bytes = buffer.split_to(size * 2);
```

```
55	                let size = buffer.read_u16::<LittleEndian>()? as usize;
(gdb) print buffer
$3 = &[u8] {data_ptr: 0x603000000110 "\001\000", length: 2}
(gdb) n
56	                let payload_bytes = buffer.split_to(size * 2);
(gdb) print buffer
$4 = &[u8] {data_ptr: 0x603000000112 "\000", length: 0}
```

**Comment by ekse** [comment]
Fixed in #25.
