### ISSUE TITLE
Out of bounds access when cursor goes out of the window

### ISSUE THREAD

**Issue by CBenoit** [Devolutions/IronRDP#261]
Here is a backtrace:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', crates/ironrdp-session/src/image.rs:308:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
   3: ironrdp_session::image::DecodedImage::recalculate_pointer_geometry
   4: ironrdp_session::image::DecodedImage::move_pointer
             at ./crates/ironrdp-session/src/image.rs:331:13
   5: ironrdp_session::active_stage::ActiveStage::process_fastpath_input
             at ./crates/ironrdp-session/src/active_stage.rs:90:29
   6: ironrdp_client::rdp::active_session::{{closure}}
             at ./crates/ironrdp-client/src/rdp.rs:191:25
   7: ironrdp_client::rdp::RdpClient::run::{{closure}}
             at ./crates/ironrdp-client/src/rdp.rs:65:14
```

**Comment by CBenoit** [comment]
Update: it’s always manifest when performing a drag operation
