### ISSUE TITLE
Panic in UserDataHeader::from_buffer due to integer overflow

### ISSUE THREAD

**Issue by ekse** [Devolutions/IronRDP#3]
In UserDataHeader::from_buffer, the program panics if `block_length` is smaller than USER_DATA_HEADER_SIZE.

https://github.com/Devolutions/IronRDP/blob/master/ironrdp/src/gcc.rs#L383

```rust
let block_length = buffer.read_u16::<LittleEndian>()?;

let mut block_data = vec![0; block_length as usize - USER_DATA_HEADER_SIZE];
```

A fix would be to return an error if block_length is smaller than USER_DATA_HEADER_SIZE.

Backtrace:

```
  #0 0x5608ba01dde1 in __sanitizer_print_stack_trace /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/llvm-project/compiler-rt/lib/asan/asan_stack.cc:86:3
    #1 0x5608ba309ff5 in fuzzer::PrintStackTrace() /home/sduquette/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerUtil.cpp:206:5
    #2 0x5608ba321bb3 in fuzzer::Fuzzer::CrashCallback() /home/sduquette/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerLoop.cpp:237:3
    #3 0x5608ba321b51 in fuzzer::Fuzzer::StaticCrashSignalCallback() /home/sduquette/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerLoop.cpp:209:6
    #4 0x5608ba314fd7 in fuzzer::CrashHandler(int, siginfo_t*, void*) /home/sduquette/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerUtilPosix.cpp:36:3
    #5 0x7f1962483f3f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x13f3f)
    #6 0x7f19622aeed6 in __libc_signal_restore_set /build/glibc-KRRWSm/glibc-2.29/signal/../sysdeps/unix/sysv/linux/internal-signals.h:84:10
    #7 0x7f19622aeed6 in gsignal /build/glibc-KRRWSm/glibc-2.29/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #8 0x7f1962290534 in abort /build/glibc-KRRWSm/glibc-2.29/stdlib/abort.c:79:7
    #9 0x5608ba346636 in std::sys::unix::abort_internal::h8e5d5e95c8d55e12 /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/sys/unix/mod.rs:155:4
    #10 0x5608ba3423e5 in std::process::abort::h872a01eae4d63489 /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/process.rs:1575:13
    #11 0x5608ba2e154b in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::hf8a82ccdc7c2a24f /home/sduquette/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/src/lib.rs:32:12
    #12 0x5608ba3457a5 in std::panicking::rust_panic_with_hook::h3ccc79b44ba3c353 /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/panicking.rs:481:16
    #13 0x5608ba345241 in std::panicking::continue_panic_fmt::h6da01b9bb2c73c79 /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/panicking.rs:384:4
    #14 0x5608ba345125 in rust_begin_unwind /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/panicking.rs:311:4
    #15 0x5608ba35c0dc in core::panicking::panic_fmt::h52bd9c4c06b66d8d /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/panicking.rs:85:13
    #16 0x5608ba35c01b in core::panicking::panic::h1fb303f1c113605d /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/panicking.rs:49:4
    #17 0x5608b9f61637 in _$LT$ironrdp..gcc..UserDataHeader$LT$T$GT$$u20$as$u20$ironrdp..PduParsing$GT$::from_buffer::h67337ec29fda00c4 /home/sduquette/git/Wayk/IronRDP/ironrdp/src/gcc.rs:383:37
    #18 0x5608b9f5bdcc in _$LT$ironrdp..gcc..ClientGccBlocks$u20$as$u20$ironrdp..PduParsing$GT$::from_buffer::h1529abd3d6024dc7 /home/sduquette/git/Wayk/IronRDP/ironrdp/src/gcc.rs:86:33
    #19 0x5608b9fa18d7 in rust_fuzzer_test_input /home/sduquette/git/Wayk/IronRDP/ironrdp/fuzz/fuzz_targets/fuzz_gcc.rs:8:12
    #20 0x5608ba2e1314 in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::h935bf9a37ba5666b /home/sduquette/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/src/lib.rs:11:8
    #21 0x5608ba338b83 in std::panicking::try::do_call::ha98d1e3726717e92 /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/panicking.rs:296:39
    #22 0x5608ba346648 in __rust_maybe_catch_panic /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libpanic_abort/lib.rs:29:4
```

**Comment by ekse** [comment]
Fixed in #4
