### ISSUE TITLE
Fuzz(pdu_decoding) - ironrdp-pdu/src/rdp/server_license/server_upgrade_license.rs:82:28: range end index 28 out of range for slice of length 16

### ISSUE THREAD

**Issue by CBenoit** [Devolutions/IronRDP#454]
Relevant workflow run: https://github.com/Devolutions/IronRDP/actions/runs/8872823505/job/24357904207

Crash artifact: [crash-360d7a779c5983f7be37b52aca392474cdc8535c.zip](https://github.com/Devolutions/IronRDP/files/15187243/crash-360d7a779c5983f7be37b52aca392474cdc8535c.zip)

Output:

```
  thread '<unnamed>' panicked at /home/runner/work/IronRDP/IronRDP/crates/ironrdp-pdu/src/rdp/server_license/server_upgrade_license.rs:82:28:
  range end index 28 out of range for slice of length 16
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/std/src/panicking.rs:652:5
     1: core::panicking::panic_fmt
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/panicking.rs:72:14
     2: core::slice::index::slice_end_index_len_fail_rt
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/slice/index.rs:66:5
     3: core::slice::index::slice_end_index_len_fail
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/slice/index.rs:59:5
     4: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/slice/index.rs:405:13
     5: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/slice/index.rs:18:9
     6: ironrdp_pdu::cursor::ReadCursor::read_slice
               at /home/runner/work/IronRDP/IronRDP/crates/ironrdp-pdu/src/cursor.rs:81:32
     7: ironrdp_pdu::rdp::server_license::server_upgrade_license::ServerUpgradeLicense::decode
               at /home/runner/work/IronRDP/IronRDP/crates/ironrdp-pdu/src/rdp/server_license/server_upgrade_license.rs:82:24
     8: <ironrdp_pdu::rdp::server_license::LicensePdu as ironrdp_pdu::PduDecode>::decode
               at /home/runner/work/IronRDP/IronRDP/crates/ironrdp-pdu/src/rdp/server_license.rs:361:20
     9: ironrdp_pdu::decode
               at /home/runner/work/IronRDP/IronRDP/crates/ironrdp-pdu/src/lib.rs:229:5
    10: ironrdp_fuzzing::oracles::pdu_decode
               at /home/runner/work/IronRDP/IronRDP/crates/ironrdp-fuzzing/src/oracles/mod.rs:38:13
    11: rust_fuzzer_test_input
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/src/lib.rs:224:17
    12: libfuzzer_sys::test_input_wrap::{{closure}}
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/src/lib.rs:61:9
    13: std::panicking::try::do_call
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/std/src/panicking.rs:559:40
    14: __rust_try
    15: std::panicking::try
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/std/src/panicking.rs:523:19
    16: std::panic::catch_unwind
               at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/std/src/panic.rs:149:14
    17: LLVMFuzzerTestOneInput
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/src/lib.rs:59:22
    18: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerLoop.cpp:612:15
    19: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEbPb
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerLoop.cpp:514:22
    20: _ZN6fuzzer6Fuzzer16MutateAndTestOneEv
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerLoop.cpp:758:25
    21: _ZN6fuzzer6Fuzzer4LoopERSt6vectorINS_9SizedFileESaIS2_EE
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerLoop.cpp:903:21
    22: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerDriver.cpp:912:10
    23: main
               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerMain.cpp:20:30
    24: __libc_start_main
    25: _start
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  ==3290== ERROR: libFuzzer: deadly signal
      #0 0x564700addfa1  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xcd7fa1) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #1 0x564701fd2520  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x21cc520) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #2 0x564701f8b48a  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x218548a) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #3 0x7f11e763641f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: c6d0d79d906d62bb768421fc6dada0d5e729f177)
      #4 0x7f11e731c00a  (/lib/x86_64-linux-gnu/libc.so.6+0x4300a) (BuildId: 87b331c034a6458c64ce09c03939e947212e18ce)
      #5 0x7f11e72fb858  (/lib/x86_64-linux-gnu/libc.so.6+0x22858) (BuildId: 87b331c034a6458c64ce09c03939e947212e18ce)
      #6 0x564702040c29  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x223ac29) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #7 0x564700a38669  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xc32669) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #8 0x564701f889c4  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x21829c4) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #9 0x564702035b45  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x222fb45) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #10 0x5647020358f3  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x222f8f3) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #11 0x564702033238  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x222d238) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #12 0x564702035626  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x222f626) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #13 0x564700a3b012  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xc35012) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #14 0x564702081fc6  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x227bfc6) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #15 0x564700a3b5c8  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xc355c8) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #16 0x56470146f11c  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x166911c) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #17 0x564701477e10  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x1671e10) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #18 0x564700b4b689  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xd45689) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #19 0x564700b17cfc  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xd11cfc) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #20 0x564701f83b6f  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x217db6f) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #21 0x564701f88bd7  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x2182bd7) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #22 0x564701f880fb  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x21820fb) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #23 0x564701f8b9cc  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x21859cc) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #24 0x564701f94e03  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x218ee03) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #25 0x564701f95bd4  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x218fbd4) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #26 0x564701f980d7  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x21920d7) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #27 0x564701fa61b9  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0x21a01b9) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #28 0x564700a3bc96  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xc35c96) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
      #29 0x7f11e72fd082  (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 87b331c034a6458c64ce09c03939e947212e18ce)
      #30 0x564700a3bdfd  (/home/runner/work/IronRDP/IronRDP/fuzz/target/x86_64-unknown-linux-gnu/release/pdu_decoding+0xc35dfd) (BuildId: 16afe1700e714de02cca877435548d8ea459ba6d)
  
  NOTE: libFuzzer has rudimentary signal handlers.
        Combine libFuzzer with AddressSanitizer or similar for better crash reports.
  SUMMARY: libFuzzer: deadly signal
  MS: 3 ShuffleBytes-ChangeBinInt-ShuffleBytes-; base unit: 4ca7f64dd5f626ee489cd296cec4e43dcf7ed468
  0xff,0x2,0x7,0x32,0x3,0x2,0xff,0xff,0x9,0x0,0x0,0x0,0xfa,0x0,0x2b,0x0,
  \377\002\0072\0
[crash-360d7a779c5983f7be37b52aca392474cdc8535c.zip](https://github.com/Devolutions/IronRDP/files/15187234/crash-360d7a779c5983f7be37b52aca392474cdc8535c.zip)
03\002\377\377\011\000\000\000\372\000+\000
  artifact_prefix='/home/runner/work/IronRDP/IronRDP/fuzz/artifacts/pdu_decoding/'; Test unit written to /home/runner/work/IronRDP/IronRDP/fuzz/artifacts/pdu_decoding/crash-360d7a779c5983f7be37b52aca392474cdc8535c
  Base64: /wIHMgMC//8JAAAA+gArAA==
  
  ────────────────────────────────────────────────────────────────────────────────
  
  Failing input:
  
  	artifacts/pdu_decoding/crash-360d7a779c5983f7be37b52aca392474cdc8535c
  
  Output of `std::fmt::Debug`:
  
  	[255, 2, 7, 50, 3, 2, 255, 255, 9, 0, 0, 0, 250, 0, 43, 0]
  
  Reproduce with:
  
  	cargo fuzz run pdu_decoding artifacts/pdu_decoding/crash-360d7a779c5983f7be37b52aca392474cdc8535c
  
  Minimize test case with:
  
  	cargo fuzz tmin pdu_decoding artifacts/pdu_decoding/crash-360d7a779c5983f7be37b52aca392474cdc8535c
```

**Comment by CBenoit** [comment]
@pacmancoder Do you think you can have a look at this?

**Comment by pacmancoder** [comment]
@CBenoit Sure I'll look into it

**Comment by pacmancoder** [comment]
@CBenoit https://github.com/Devolutions/IronRDP/pull/455
